# -*- coding: utf-8 -*-
"""Chilli_Disease_Training

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XOxzCePgTySGTG1-tTiNsaJpynnjJMjb
"""

# ================================================================
# CHILLI LEAF DISEASE DETECTION — COMPLETE COLAB TRAINING CODE
# ================================================================
# STEP 1: Mounting Google Drive
# ================================================================

from google.colab import drive
drive.mount('/content/drive')
print("Drive mounted successfully!")

# ================================================================
# STEP 2: Checking  dataset
# ================================================================

import os

DATASET_PATH = "/content/drive/MyDrive/chilli_project/dataset"

print("Checking dataset...\n")
total = 0
CLASS_NAMES = [
    "anthracnose",
    "bacterial_spot",
    "cercospora_spot",
    "healthy",
    "leaf_curl",
    "mosaic_virus",
    "powdery_mildew",
    "thrips_damage",
]

for cls in CLASS_NAMES:
    path = os.path.join(DATASET_PATH, cls)
    if os.path.exists(path):
        count = len(os.listdir(path))
        total += count
        status = "✓ Good" if count >= 150 else "⚠ Low — augmentation will fix"
        print(f"  {cls:<20} {count:>5} images   {status}")
    else:
        print(f"  {cls:<20} FOLDER NOT FOUND!")

print(f"\nTotal images: {total}")
print("Dataset check complete!")

# ================================================================
# STEP 3: Copying dataset to Colab local storage (makes training fast)
# This takes 5-10 minutes but makes training 5x faster
# ================================================================

import shutil, time

src = "/content/drive/MyDrive/chilli_project/dataset"
dst = "/content/dataset"

if os.path.exists(dst):
    print("Dataset already copied to local storage!")
else:
    print("Copying dataset from Drive to local storage...")
    print("This takes 5-10 minutes...\n")
    start = time.time()
    shutil.copytree(src, dst)
    elapsed = time.time() - start
    print(f"Copy complete in {elapsed/60:.1f} minutes!")
    print("Verifying:")
    for cls in CLASS_NAMES:
        count = len(os.listdir(os.path.join(dst, cls)))
        print(f"  {cls:<20} {count} images")

# ================================================================
# STEP 4: Balancing dataset — 600 images per class
# This fixes class imbalance which causes biased training
# ================================================================

import random

src_balanced_from = "/content/dataset"
dst_balanced = "/content/dataset_balanced"
MAX_PER_CLASS = 600

if os.path.exists(dst_balanced):
    shutil.rmtree(dst_balanced)

os.makedirs(dst_balanced)
print(f"Creating balanced dataset — {MAX_PER_CLASS} images per class...\n")

for cls in CLASS_NAMES:
    src_cls = os.path.join(src_balanced_from, cls)
    dst_cls = os.path.join(dst_balanced, cls)
    os.makedirs(dst_cls)

    all_imgs = [f for f in os.listdir(src_cls)
                if f.lower().endswith(('.jpg', '.jpeg', '.png'))]

    if len(all_imgs) == 0:
        print(f"  {cls}: NO IMAGES FOUND!")
        continue

    if len(all_imgs) < MAX_PER_CLASS:
        # Duplicate images to reach target
        for img in all_imgs:
            shutil.copy(os.path.join(src_cls, img),
                       os.path.join(dst_cls, img))
        extra = MAX_PER_CLASS - len(all_imgs)
        for i in range(extra):
            pick = random.choice(all_imgs)
            shutil.copy(os.path.join(src_cls, pick),
                       os.path.join(dst_cls, f"dup_{i:04d}_{pick}"))
        print(f"  {cls:<20} {len(all_imgs)} original → duplicated to {MAX_PER_CLASS} ✓")
    else:
        selected = random.sample(all_imgs, MAX_PER_CLASS)
        for img in selected:
            shutil.copy(os.path.join(src_cls, img),
                       os.path.join(dst_cls, img))
        print(f"  {cls:<20} {MAX_PER_CLASS} images selected ✓")

print(f"\nBalanced dataset ready! Total: {len(CLASS_NAMES) * MAX_PER_CLASS} images")

# ================================================================
# STEP 5: Install and import all libraries
# ================================================================

import tensorflow as tf
from tensorflow.keras import layers, Model
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import numpy as np
import matplotlib.pyplot as plt

print(f"TensorFlow version: {tf.__version__}")
print(f"GPU available: {len(tf.config.list_physical_devices('GPU')) > 0}")
print("All libraries imported!")

# ================================================================
# STEP 6: Create data generators
# ================================================================

IMAGE_SIZE   = 96
BATCH_SIZE   = 32
NUM_CLASSES  = 8
DATASET_PATH_BALANCED = "/content/dataset_balanced"

# Training generator with augmentation
train_gen = ImageDataGenerator(
    rescale            = 1./255,
    validation_split   = 0.2,
    rotation_range     = 25,
    horizontal_flip    = True,
    vertical_flip      = True,
    zoom_range         = 0.15,
    brightness_range   = [0.8, 1.2],
    shear_range        = 0.1,
    width_shift_range  = 0.1,
    height_shift_range = 0.1,
).flow_from_directory(
    DATASET_PATH_BALANCED,
    target_size  = (IMAGE_SIZE, IMAGE_SIZE),
    batch_size   = BATCH_SIZE,
    class_mode   = "categorical",
    subset       = "training",
    classes      = CLASS_NAMES,
    shuffle      = True,
)

# Validation generator — no augmentation
val_gen = ImageDataGenerator(
    rescale          = 1./255,
    validation_split = 0.2,
).flow_from_directory(
    DATASET_PATH_BALANCED,
    target_size  = (IMAGE_SIZE, IMAGE_SIZE),
    batch_size   = BATCH_SIZE,
    class_mode   = "categorical",
    subset       = "validation",
    classes      = CLASS_NAMES,
    shuffle      = False,
)

print(f"Training images  : {train_gen.samples}")
print(f"Validation images: {val_gen.samples}")
print(f"Steps per epoch  : {len(train_gen)}")
print(f"Classes          : {train_gen.class_indices}")

# ================================================================
# STEP 7: Build MobileNetV2 model
# alpha=0.35 means 35% width — gives small model that fits ESP32
# ================================================================

# Load pretrained MobileNetV2 — already knows edges, textures, shapes
base = MobileNetV2(
    input_shape = (IMAGE_SIZE, IMAGE_SIZE, 3),
    include_top = False,      # Remove ImageNet classifier
    weights     = "imagenet", # Use pretrained weights
    alpha       = 0.35,       # 35% width — small enough for ESP32
)
base.trainable = False  # Freeze base layers for Phase 1

# Add your disease classification layers on top
x   = base.output
x   = layers.GlobalAveragePooling2D()(x)  # Flatten feature maps
x   = layers.Dense(128, activation="relu")(x)
x   = layers.Dropout(0.4)(x)              # Prevent overfitting
out = layers.Dense(NUM_CLASSES, activation="softmax")(x)  # 8 outputs

model = Model(inputs=base.input, outputs=out)

model.compile(
    optimizer = tf.keras.optimizers.Adam(learning_rate=0.001),
    loss      = "categorical_crossentropy",
    metrics   = ["accuracy"]
)

print(f"\nModel built successfully!")
print(f"Total parameters : {model.count_params():,}")
print(f"Base layers      : {len(base.layers)}")
print(f"Input shape      : {model.input_shape}")
print(f"Output shape     : {model.output_shape}")

# ================================================================
# STEP 8: Phase 1 Training — Top layers only
# Trains your new classification head
# Base model stays frozen
# Expected accuracy: 75-87%
# Takes about 10-15 minutes
# ================================================================

print("\n=== PHASE 1: Training top classification layers ===")
print("Base model frozen. Only new Dense layers are training.")
print("Expected accuracy: 75-87%\n")

h1 = model.fit(
    train_gen,
    validation_data = val_gen,
    epochs          = 25,
    callbacks = [
        tf.keras.callbacks.EarlyStopping(
            monitor              = "val_accuracy",
            patience             = 6,
            restore_best_weights = True,
            verbose              = 1
        ),
        tf.keras.callbacks.ReduceLROnPlateau(
            monitor  = "val_loss",
            factor   = 0.3,
            patience = 3,
            verbose  = 1
        ),
        tf.keras.callbacks.ModelCheckpoint(
            "/content/best_phase1.keras",
            monitor        = "val_accuracy",
            save_best_only = True,
            verbose        = 0
        ),
    ],
    verbose = 1,
)

l1, a1 = model.evaluate(val_gen, verbose=0)
print(f"\nPhase 1 complete!")
print(f"Validation accuracy: {a1*100:.1f}%")
print(f"Validation loss    : {l1:.4f}")

# ================================================================
# STEP 9: Phase 2 Training — Fine tuning
# Unfreeze last 10 layers of base model
# Use very small learning rate to avoid catastrophic forgetting
# Expected accuracy: 85-92%
# Takes about 15-20 minutes
# ================================================================

print("\n=== PHASE 2: Fine-tuning last 10 base layers ===")
print("Learning rate reduced 200x to prevent catastrophic forgetting")
print("Expected accuracy: 85-92%\n")

# Unfreeze only last 10 layers of base
base.trainable = True
for layer in base.layers[:-10]:
    layer.trainable = False

trainable_count = sum(1 for l in model.layers if l.trainable)
print(f"Trainable layers now: {trainable_count}")

# Much smaller learning rate for fine-tuning
model.compile(
    optimizer = tf.keras.optimizers.Adam(learning_rate=0.000005),
    loss      = "categorical_crossentropy",
    metrics   = ["accuracy"]
)

h2 = model.fit(
    train_gen,
    validation_data = val_gen,
    epochs          = 25,
    callbacks = [
        tf.keras.callbacks.EarlyStopping(
            monitor              = "val_accuracy",
            patience             = 6,
            restore_best_weights = True,
            verbose              = 1
        ),
        tf.keras.callbacks.ReduceLROnPlateau(
            monitor  = "val_loss",
            factor   = 0.3,
            patience = 3,
            verbose  = 1
        ),
        tf.keras.callbacks.ModelCheckpoint(
            "/content/best_model.keras",
            monitor        = "val_accuracy",
            save_best_only = True,
            verbose        = 1
        ),
    ],
    verbose = 1,
)

l2, a2 = model.evaluate(val_gen, verbose=0)
print(f"\n=== TRAINING COMPLETE ===")
print(f"Phase 1 accuracy: {a1*100:.1f}%")
print(f"Phase 2 accuracy: {a2*100:.1f}%")

if a2 >= 0.85:
    print("Excellent! Accuracy above 85% — proceed to conversion.")
elif a2 >= 0.75:
    print("Good accuracy. Proceed to conversion.")
else:
    print("Accuracy below 75%. Consider adding more images.")

# ================================================================
# STEP 10: Save accuracy graph for your project report
# ================================================================

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

acc      = h1.history["accuracy"]     + h2.history["accuracy"]
val_acc  = h1.history["val_accuracy"] + h2.history["val_accuracy"]
loss     = h1.history["loss"]         + h2.history["loss"]
val_loss = h1.history["val_loss"]     + h2.history["val_loss"]
ep       = range(len(acc))
split    = len(h1.history["accuracy"])

axes[0].plot(ep, acc,     color="blue",  linewidth=2, label="Training Accuracy")
axes[0].plot(ep, val_acc, color="green", linewidth=2, label="Validation Accuracy")
axes[0].axvline(x=split-1, color="red", linestyle="--", linewidth=1.5,
                label=f"Fine-tune starts (Epoch {split})")
axes[0].set_title("Model Accuracy Over Epochs", fontsize=14, fontweight="bold")
axes[0].set_xlabel("Epoch"); axes[0].set_ylabel("Accuracy")
axes[0].legend(); axes[0].grid(True, alpha=0.3)
axes[0].set_ylim([0, 1])

axes[1].plot(ep, loss,     color="blue",  linewidth=2, label="Training Loss")
axes[1].plot(ep, val_loss, color="green", linewidth=2, label="Validation Loss")
axes[1].axvline(x=split-1, color="red", linestyle="--", linewidth=1.5,
                label=f"Fine-tune starts (Epoch {split})")
axes[1].set_title("Model Loss Over Epochs", fontsize=14, fontweight="bold")
axes[1].set_xlabel("Epoch"); axes[1].set_ylabel("Loss")
axes[1].legend(); axes[1].grid(True, alpha=0.3)

plt.suptitle(
    f"Chilli Leaf Disease Detection — MobileNetV2 Training\n"
    f"Final Validation Accuracy: {a2*100:.1f}% | 8 Disease Classes | 4800 Images",
    fontsize=13, fontweight="bold"
)
plt.tight_layout()
plt.savefig("/content/training_graph.png", dpi=150, bbox_inches="tight")
plt.show()
print("Training graph saved as training_graph.png!")

# ================================================================
# STEP 11: Convert to TFLite INT8 for ESP32 deployment
# Shrinks model from ~2MB to ~766KB
# INT8 = 8-bit integer (1 byte per weight instead of 4 bytes)
# ================================================================

print("\nConverting to TFLite INT8 format...")
print("This may take 5-10 minutes...")

def representative_dataset():
    """Feed 200 sample images to calibrate INT8 quantization"""
    count = 0
    for imgs, _ in val_gen:
        for img in imgs:
            yield [np.expand_dims(img, axis=0).astype(np.float32)]
            count += 1
            if count >= 200:
                return

converter = tf.lite.TFLiteConverter.from_keras_model(model)

# Enable quantization
converter.optimizations             = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset    = representative_dataset
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type      = tf.uint8   # Input: 0-255 integers
converter.inference_output_type     = tf.uint8   # Output: 0-255 integers

# Convert
tflite_model = converter.convert()

# Save TFLite file
with open("/content/chilli_disease.tflite", "wb") as f:
    f.write(tflite_model)

size_kb = len(tflite_model) / 1024
print(f"\nTFLite model saved!")
print(f"Model size: {size_kb:.1f} KB")

if size_kb < 1000:
    print("PERFECT — fits in ESP32 4MB flash storage!")
elif size_kb < 4000:
    print("OK — fits in ESP32 with SPIFFS")
else:
    print("Too large for ESP32 — contact for further optimization")

# ================================================================
# STEP 12: Convert TFLite to C header file for Arduino
# This creates chilli_model.h that goes in Arduino project folder
# ================================================================

os.system("xxd -i /content/chilli_disease.tflite > /content/chilli_model.h")

header_size = os.path.getsize("/content/chilli_model.h") / 1024
print(f"C header file created: {header_size:.1f} KB")

# Verify it looks correct
with open("/content/chilli_model.h", "r") as f:
    first_line = f.readline().strip()
    print(f"First line of header: {first_line[:60]}...")
    print("Header file looks correct!")

# ================================================================
# STEP 13: Test model on random images before downloading
# ================================================================

from tensorflow.keras.preprocessing.image import load_img, img_to_array

print("\nTesting model on 15 random validation images...\n")

correct = 0
total_test = 15

for _ in range(total_test):
    cls = random.choice(CLASS_NAMES)
    cls_path = os.path.join(DATASET_PATH_BALANCED, cls)
    img_file = random.choice(os.listdir(cls_path))
    img_path = os.path.join(cls_path, img_file)

    img = load_img(img_path, target_size=(IMAGE_SIZE, IMAGE_SIZE))
    arr = img_to_array(img) / 255.0
    arr = np.expand_dims(arr, axis=0)

    pred     = model.predict(arr, verbose=0)
    pred_cls = CLASS_NAMES[np.argmax(pred)]
    conf     = np.max(pred) * 100
    ok       = pred_cls == cls

    if ok:
        correct += 1

    symbol = "✓" if ok else "✗"
    print(f"{symbol} Actual: {cls:<20} Predicted: {pred_cls:<20} ({conf:.0f}%)")

print(f"\nTest result: {correct}/{total_test} correct = {correct/total_test*100:.0f}%")

# ================================================================
# STEP 14: Download all files to your laptop
# Check your browser Downloads folder after running this
# ================================================================

from google.colab import files

print("\nDownloading all files to your laptop...")
print("Check browser Downloads folder\n")

print("1. Downloading chilli_disease.tflite ...")
files.download("/content/chilli_disease.tflite")

print("2. Downloading chilli_model.h ...")
files.download("/content/chilli_model.h")

print("3. Downloading training_graph.png ...")
files.download("/content/training_graph.png")

print("4. Downloading best_model.keras ...")
files.download("/content/best_model.keras")

print("\n" + "="*55)
print("ALL DONE!")
print("="*55)
print(f"Final model accuracy : {a2*100:.1f}%")
print(f"TFLite model size    : {size_kb:.1f} KB")
print("\nSend these 2 files to your friend:")
print("  → chilli_disease.tflite  (goes into ESP32)")
print("  → chilli_model.h         (goes into Arduino folder)")
print("\nKeep these 2 files yourself:")
print("  → training_graph.png     (put in project report)")
print("  → best_model.keras       (backup on your laptop)")